### ISSUE TITLE
finalize the name for this sim and its repository

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#1]
graphing-slope-intercept is the (possibly) temporary name that we went with in https://github.com/phetsims/graphing-lines/issues/66#issuecomment-284832604.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/66#issuecomment-284790693, I said:

> Some possible names:
> 
> Graphing Slope-Intercept Lines
Graphing Lines: Slope-Intercept
Slope-Intercept Form
Slope-Intercept Lines

**Comment by samreid** [comment]
"Graphing Slopes & Intercepts"

**Comment by pixelzoom** [comment]
This simulation is now feature complete, so time to make a decision about it's name.

**Comment by pixelzoom** [comment]
This simulation is now feature complete, so time to make a decision about it's name. The title is currently "Graphing Slope-Intercept", and the repository name is graphing-slope-intercept.

**Comment by amanda-phet** [comment]
Since this is a spinoff of Graphing Lines, I would like it to start with "Graphing..." so they are near each other in our listed sims. The good thing about the current name is that it is short, while any other possibilities are much longer (Graphing Slope-Intercept Lines, Graphing Lines: Slope-Intercept Form, etc.). 

I like the current name and think we should keep it.

**Comment by pixelzoom** [comment]
Since we're keeping the current name, nothing for me to do (hurray!)

Closing.
