### ISSUE TITLE
should this sim include the "Slope" screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-slope-intercept#3]
The [design document](https://docs.google.com/document/d/1ztSRN1YE1BIGI1rsCBnZXzZQYvelSFySp4sDHPh2OJs/edit#) currently does not include the Slope screen.  But in our initial discussions in phetsims/graphing-lines#66, I thought it was included. 

In https://github.com/phetsims/graphing-slope-intercept/issues/2#issuecomment-284879634, @amanda-phet said:
> It is an incomplete document, but I wasn't sure about that particular screen and the final decision. I don't have a strong opinion either way. There aren't any game challenges based on the slope screen in either game which is why I am not sure about the best way to go.

**Comment by amanda-phet** [comment]
Since we are trying to isolate the slope-intercept form of a line, I don't see a teacher wanting to use the slope screen in the same lesson. I'm not saying it's harmful to include it, but since it already exists in the Graphing Lines sim I don't see the value of including this screen in this version of the sim. 

@ariel-phet Did you have a reason for wanting to include the slope screen?

**Comment by ariel-phet** [comment]
I don't really have a strong opinion, I would be fine not including it.

**Comment by amanda-phet** [comment]
Thanks @ariel-phet .

@pixelzoom Let's move forward with only including the point-slope screen and the line game screen.

**Comment by pixelzoom** [comment]
Slope screen has been removed, closing.
