### ISSUE TITLE
Automated testing error

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/graphing-slope-intercept#9]
Fails to launch or build:
```
graphing-slope-intercept : build
Failure to grunt snapshot-1489640654197/graphing-slope-intercept:
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task
requirejs failed
Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1489640654197/graphing-lines/js/linegame/model/ValuePool.js'
In module tree:
    graphing-slope-intercept-main
      GRAPHING_SLOPE_INTERCEPT/linegame/GSILineGameScreen
        GRAPHING_SLOPE_INTERCEPT/linegame/model/GSILineGameModel
          GRAPHING_SLOPE_INTERCEPT/linegame/model/GSIChallengeFactory1


Running "after-requirejs-build" task
>> Unused string: key=GRAPHING_SLOPE_INTERCEPT/graphing-slope-intercept.title, value=Graphing Slope-Intercept
Fatal error: missing entry for sim title, key = GRAPHING_SLOPE_INTERCEPT/graphing-slope-intercept.title


Approximately 3/15/2017, 11:04:14 PM
```

**Comment by pixelzoom** [comment]
This error was caused by some stuff that apparently didn't get pushed from my working copy. I'll attribute that to the flakey wifi connection at the airport.
>
 Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1489640654197/graphing-lines/js/linegame/model/ValuePool.js'

This error has me stumped:
> >> Unused string: key=GRAPHING_SLOPE_INTERCEPT/graphing-slope-intercept.title, value=Graphing Slope-Intercept
Fatal error: missing entry for sim title, key = GRAPHING_SLOPE_INTERCEPT/graphing-slope-intercept.title�

I'm not sure where the extra character is coming from at the end of the string key (`graphing-slope-intercept.title�`).  I inspected `graphing-slope-intercept-strings_en.json` and chipper's `active-*` files with vi, and I don't see it there.   And I also don't see this error when I build.   Any ideas?...

**Comment by pixelzoom** [comment]
The `missing entry for sim title` comes from createHTMLFiles.js:

```js
49 assert( simTitle, 'missing entry for sim title, key = ' + buildConfig.simTitleStringKey );
```

`buildConfig.simTitleStingKey` is defined in getBuilderConfig.js:

```js
317   buildConfig.simTitleStringKey = buildConfig.requirejsNamespace + '/' + buildConfig.name + '.title'; // REPO/repo.name
```

So I'm again stumped about how that extra char could appear.

@jonathanolson Is it possible that the extra char did not actually appear in the console output, and that you accidentally added it when creating this GitHub issue?

**Comment by pixelzoom** [comment]
I also did a string search in all repos for `title�` in all repos (all file types), and it's not found.

**Comment by pixelzoom** [comment]
I cannot reproduce this build error with HEAD of master:

```
% grunt 
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done.
%
```

I'm concluding that this is a problem with "continuous testing", which I don't know enough about to troubleshoot.   So I'm reassigning this to @jonathanolson to investigate.  @phet-steele please report if you see this error during your weekly testing.

**Comment by jonathanolson** [comment]
> I'm concluding that this is a problem with "continuous testing", which I don't know enough about to troubleshoot. So I'm reassigning this to @jonathanolson to investigate. @phet-steele please report if you see this error during your weekly testing.

The string checker may have complained only when there was a missing require.js dependency?

It's definitely building/running fine now, closing.
